import { Product } from "./types";

// Datos de respaldo: se usan cuando Strapi no está disponible,
// de modo que la web funcione en desarrollo sin backend levantado.
export const mockProducts: Product[] = [
  {
    id: 1,
    slug: "auraledge-pro-x",
    name: "AuralEdge Pro X",
    subtitle: "Studio grade precision for audiophiles",
    description:
      "Experience audio grade sound with dual dynamic drivers and Hi-Res Audio. Designed for precision, deep bass and all day comfort.",
    price: 349.99,
    compareAtPrice: 499.99,
    tag: "Best Seller",
    badge: "-30%",
    features: ["40h Battery", "Dual Drivers", "Hi-Res Audio"],
    batteryHours: 40,
    noiseCancelling: 99,
    bestValue: true,
    highlight: true,
    image: null,
  },
  {
    id: 2,
    slug: "auraledge-studio",
    name: "AuralEdge Studio",
    subtitle: "Reference sound for creators",
    description:
      "Reference-grade planar magnetic drivers tuned for mixing and mastering. Flat response, zero coloration.",
    price: 279.99,
    compareAtPrice: 369.99,
    tag: "Pro",
    badge: "-25%",
    features: ["50h Battery", "Planar Magnetic", "USB-C DAC"],
    batteryHours: 50,
    noiseCancelling: 96,
    bestValue: true,
    highlight: false,
    image: null,
  },
  {
    id: 3,
    slug: "auraledge-one",
    name: "AuralEdge One",
    subtitle: "Premium wireless for daily use",
    description:
      "Everyday premium wireless with adaptive noise cancellation and fast charging for life on the move.",
    price: 199.99,
    compareAtPrice: null,
    tag: "Best Seller",
    badge: null,
    features: ["ANC", "30h", "Fast Charge"],
    batteryHours: 30,
    noiseCancelling: 94,
    bestValue: false,
    highlight: false,
    image: null,
  },
  {
    id: 4,
    slug: "auraledge-two",
    name: "AuralEdge Two",
    subtitle: "Premium wireless for daily use",
    description:
      "Hi-Res certified with multipoint pairing and 40 hours of playback for uninterrupted listening.",
    price: 229.99,
    compareAtPrice: null,
    tag: "New",
    badge: null,
    features: ["Hi-Res", "40h", "Multipoint"],
    batteryHours: 40,
    noiseCancelling: 95,
    bestValue: false,
    highlight: false,
    image: null,
  },
  {
    id: 5,
    slug: "auraledge-air",
    name: "AuralEdge Air",
    subtitle: "Ultra-light everyday comfort",
    description:
      "Featherweight design with Bluetooth 5.4 and 35 hours of battery — comfort you forget you're wearing.",
    price: 159.99,
    compareAtPrice: 189.99,
    tag: "Popular",
    badge: "-15%",
    features: ["Lightweight", "35h", "BT 5.4"],
    batteryHours: 35,
    noiseCancelling: 90,
    bestValue: true,
    highlight: false,
    image: null,
  },
];
