import { Product } from "./types";

// Datos de respaldo: se usan cuando Strapi no está disponible, de modo que la
// web funcione en desarrollo sin backend. Los `previewUrl` apuntan a clips de
// demo públicos (SoundHelix) solo para poder probar el reproductor en local.
export const mockProducts: Product[] = [
  {
    id: 1,
    slug: "midnight-trap",
    name: "Midnight Trap",
    subtitle: "Beat oscuro con 808s pesados",
    description:
      "Instrumental de trap con 808s profundos, hi-hats rápidos y una melodía nocturna. Ideal para flows agresivos.",
    price: 12990,
    compareAtPrice: 17990,
    tag: "Best Seller",
    badge: "-30%",
    features: ["Mezcla lista", "WAV + MP3", "Licencia estándar"],
    genre: "Trap",
    bpm: 140,
    musicalKey: "Fm",
    durationSeconds: 182,
    previewSeconds: 30,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    bestValue: true,
    highlight: true,
    image: null,
  },
  {
    id: 2,
    slug: "perreo-neon",
    name: "Perreo Neón",
    subtitle: "Reggaetón perreo con dembow moderno",
    description:
      "Base de reggaetón con dembow contundente, sintes neón y groove pegajoso pensado para la pista.",
    price: 14990,
    compareAtPrice: null,
    tag: "Pro",
    badge: null,
    features: ["Stems incluidos", "WAV + MP3", "Licencia premium"],
    genre: "Reggaetón",
    bpm: 96,
    musicalKey: "Am",
    durationSeconds: 168,
    previewSeconds: 25,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    bestValue: true,
    highlight: false,
    image: null,
  },
  {
    id: 3,
    slug: "drill-santiago",
    name: "Drill Santiago",
    subtitle: "UK drill con sliding 808s",
    description:
      "Instrumental drill con 808s deslizantes, hats triplet y atmósfera fría. Crudo y directo.",
    price: 11990,
    compareAtPrice: null,
    tag: "New",
    badge: null,
    features: ["Mezcla lista", "MP3", "Licencia estándar"],
    genre: "Drill",
    bpm: 144,
    musicalKey: "C#m",
    durationSeconds: 155,
    previewSeconds: 20,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    bestValue: false,
    highlight: false,
    image: null,
  },
  {
    id: 4,
    slug: "afrobeat-verano",
    name: "Afrobeat Verano",
    subtitle: "Afrobeat cálido y bailable",
    description:
      "Groove afrobeat luminoso con percusión orgánica y melodías cálidas, perfecto para hits de verano.",
    price: 13990,
    compareAtPrice: 16990,
    tag: "Popular",
    badge: "-15%",
    features: ["Stems incluidos", "WAV + MP3", "Licencia premium"],
    genre: "Afrobeat",
    bpm: 102,
    musicalKey: "G",
    durationSeconds: 174,
    previewSeconds: 30,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    bestValue: true,
    highlight: false,
    image: null,
  },
  {
    id: 5,
    slug: "rkt-bajo-fuego",
    name: "RKT Bajo Fuego",
    subtitle: "RKT/guaracha energético",
    description:
      "Base de RKT acelerada con kick guaracha y sintes filosos para prender cualquier fiesta.",
    price: 10990,
    compareAtPrice: null,
    tag: "Best Seller",
    badge: null,
    features: ["Mezcla lista", "WAV + MP3", "Licencia estándar"],
    genre: "RKT",
    bpm: 130,
    musicalKey: "Dm",
    durationSeconds: 160,
    previewSeconds: 25,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    bestValue: false,
    highlight: false,
    image: null,
  },
];
