import { Menu, Product } from "./types";

// Datos de respaldo: se usan cuando Strapi no está disponible, de modo que la
// web funcione en desarrollo sin backend. Los `previewUrl` apuntan a clips de
// demo públicos (SoundHelix) solo para poder probar el reproductor en local.
export const mockProducts: Product[] = [
  {
    id: 1,
    slug: "midnight-trap",
    name: "Midnight Trap",
    subtitle: "Beat oscuro con 808s pesados",
    description:
      "Instrumental de trap con 808s profundos, hi-hats rápidos y una melodía nocturna. Ideal para flows agresivos.",
    price: 12990,
    compareAtPrice: 17990,
    tag: "Best Seller",
    badge: "-30%",
    features: ["Mezcla lista", "WAV + MP3", "Licencia estándar"],
    genre: "Trap",
    bpm: 140,
    musicalKey: "Fm",
    durationSeconds: 182,
    previewSeconds: 30,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    category: "Plantillas mezcla beats",
    bestValue: true,
    highlight: true,
    menuSlugs: ["beats"],
    subcategorySlugs: ["trap"],
    subcategoryNames: ["Trap"],
  },
  {
    id: 2,
    slug: "perreo-neon",
    name: "Perreo Neón",
    subtitle: "Reggaetón perreo con dembow moderno",
    description:
      "Base de reggaetón con dembow contundente, sintes neón y groove pegajoso pensado para la pista.",
    price: 14990,
    compareAtPrice: null,
    tag: "Pro",
    badge: null,
    features: ["Stems incluidos", "WAV + MP3", "Licencia premium"],
    genre: "Reggaetón",
    bpm: 96,
    musicalKey: "Am",
    durationSeconds: 168,
    previewSeconds: 25,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    category: "Plantillas vocales",
    bestValue: true,
    highlight: false,
    menuSlugs: ["beats"],
    subcategorySlugs: ["reggaeton"],
    subcategoryNames: ["Reggaetón"],
  },
  {
    id: 3,
    slug: "drill-santiago",
    name: "Drill Santiago",
    subtitle: "UK drill con sliding 808s",
    description:
      "Instrumental drill con 808s deslizantes, hats triplet y atmósfera fría. Crudo y directo.",
    price: 11990,
    compareAtPrice: null,
    tag: "New",
    badge: null,
    features: ["Mezcla lista", "MP3", "Licencia estándar"],
    genre: "Drill",
    bpm: 144,
    musicalKey: "C#m",
    durationSeconds: 155,
    previewSeconds: 20,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    category: "Plantillas masterización",
    bestValue: false,
    highlight: false,
    menuSlugs: ["beats"],
    subcategorySlugs: ["drill"],
    subcategoryNames: ["Drill"],
  },
  {
    id: 4,
    slug: "afrobeat-verano",
    name: "Afrobeat Verano",
    subtitle: "Afrobeat cálido y bailable",
    description:
      "Groove afrobeat luminoso con percusión orgánica y melodías cálidas, perfecto para hits de verano.",
    price: 13990,
    compareAtPrice: 16990,
    tag: "Popular",
    badge: "-15%",
    features: ["Stems incluidos", "WAV + MP3", "Licencia premium"],
    genre: "Afrobeat",
    bpm: 102,
    musicalKey: "G",
    durationSeconds: 174,
    previewSeconds: 30,
    previewUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    category: "Plantillas mezcla beats",
    bestValue: true,
    highlight: false,
    menuSlugs: ["beats"],
    subcategorySlugs: ["trap"],
    subcategoryNames: ["Trap"],
  },
  {
    id: 5,
    slug: "pack-vocal-pro",
    name: "Pack Plantilla Vocal Pro",
    subtitle: "Plantilla de mezcla vocal (.zip)",
    description:
      "Plantilla lista para mezclar voces: cadena de efectos, presets y sesión de ejemplo. Descarga en .zip.",
    price: 9990,
    compareAtPrice: null,
    tag: "Plantilla",
    badge: null,
    features: [".zip descargable", "Presets incluidos", "Compatible FL/Ableton"],
    genre: null,
    bpm: null,
    musicalKey: null,
    durationSeconds: null,
    previewSeconds: null,
    previewUrl: null,
    category: "Plantillas vocales",
    bestValue: false,
    highlight: true,
    menuSlugs: ["plantillas"],
    subcategorySlugs: ["plantillas-vocales"],
    subcategoryNames: ["Plantillas vocales"],
  },
];

/** Menús de respaldo (fallback del navbar cuando no hay Strapi). */
export const mockMenus: Menu[] = [
  {
    id: 1,
    name: "Beats",
    slug: "beats",
    order: 1,
    icon: "Disc3",
    subcategories: [
      { id: 1, name: "Trap", slug: "trap", menuSlug: "beats" },
      { id: 2, name: "Reggaetón", slug: "reggaeton", menuSlug: "beats" },
      { id: 3, name: "Drill", slug: "drill", menuSlug: "beats" },
    ],
  },
  {
    id: 2,
    name: "Plantillas",
    slug: "plantillas",
    order: 2,
    icon: "LayoutTemplate",
    subcategories: [
      { id: 4, name: "Plantillas vocales", slug: "plantillas-vocales", menuSlug: "plantillas" },
      { id: 5, name: "Plantillas mezcla beats", slug: "plantillas-mezcla-beats", menuSlug: "plantillas" },
      { id: 6, name: "Plantillas masterización", slug: "plantillas-masterizacion", menuSlug: "plantillas" },
    ],
  },
];
